describe('first',()=>{
    it('second',()=>{
        cy.visit('https://vetcastle.com')
        cy.url().should ('eq','https://vetcastle.com/')
        cy.get('.grow > :nth-child(2) > .font-medium').click()
        cy.url().should('eq',"https://vetcastle.com/signin")
        cy.get(':nth-child(3) > .text-gray-600').click()
        cy.get('#username').type("srivathsandv2")
        cy.get('#password').type("1SDE@mayim")
        cy.get('.btn').click()
        cy.visit("https://vetcastle.com/maindashboard")
        cy.reload()
        cy.get('[href="/inventory"] > .MuiListItemIcon-root').click()
        cy.url().should('eq',"https://vetcastle.com/inventory")
        cy.get('.MuiGrid-container > :nth-child(3) > .MuiButtonBase-root').click()
        cy.get('.MuiFormControl-root > .MuiInputBase-root > .MuiSelect-select').click()
    })
})