name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '20'
      - run: npm install --force
      - run: npm install cypress --save-dev --force
      - name: Cypress run
        run : npx cypress run